public class SumOfNumbers1  
{  
public static void main(String args[])   
{  

  int n1 = 225, n2 = 115, sum;
  sum = n1 + n2;
  System.out.println("The sum of numbers is: "+sum);  
}  
}  

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
